export const dogsText = {
  title: 'Hunde',
  add: 'Hund hinzufügen',
  firstDog: 'Ersten Hund anlegen',
  newTitle: 'Neuer Hund',
  editTitle: 'Hund bearbeiten',
  cancel: 'Abbrechen',
  save: 'Sichern',
  saved: (name: string) => `${name} gesichert.`,
  empty: 'Noch kein Hund eingetragen.',
  archivedTitle: 'Archiviert',
  archivedNote: 'Archiviert: Erinnerungen enden, die Einträge bleiben lesbar.',
  notFound: 'Diesen Hund gibt es nicht mehr.',
  sections: {
    about: 'Über den Hund',
    chip: 'Chip und AMICUS',
    vet: 'Tierarztpraxis',
    insurance: 'Versicherung',
    care: 'Für die Betreuung',
  },
  fields: {
    name: 'Name',
    birthDate: 'Geburtsdatum',
    birthDateHint: 'Zum Beispiel 14.05.2021',
    birthYear: 'Oder nur das Geburtsjahr',
    breed: 'Rasse oder Mischung',
    sex: 'Geschlecht',
    neutered: 'Kastriert',
    colorMarkings: 'Farbe und Merkmale',
    chipNumber: 'Chipnummer',
    amicusRegistered: 'Bei AMICUS registriert',
    vetName: 'Name der Praxis',
    vetPhone: 'Telefon der Praxis',
    vetAddress: 'Adresse der Praxis',
    insuranceName: 'Versicherung',
    insurancePolicy: 'Policennummer',
    insurancePhone: 'Telefon der Versicherung',
    food: 'Futter, Mengen und Zeiten',
    allergies: 'Allergien',
    careNotes: 'Hinweise für die Betreuung',
  },
  sex: { male: 'Rüde', female: 'Hündin' },
  chipCountry: { CH: 'Chipnummer aus der Schweiz' },
  photo: {
    take: 'Foto aufnehmen',
    choose: 'Foto wählen',
    replace: 'Foto ersetzen',
    label: (name: string) => `Foto von ${name}`,
    busy: 'Foto wird vorbereitet …',
    unsafe:
      'Dieses Foto liess sich nicht von seinen Standortdaten befreien und wird darum nicht gespeichert. Versuch es mit einem anderen Foto.',
    failed: 'Das Foto liess sich nicht übernehmen. Versuch es nochmals.',
    denied:
      'Die App darf die Kamera nicht benutzen. Du kannst ein Foto wählen oder die Kamera in den Einstellungen des Geräts erlauben.',
    openSettings: 'Einstellungen öffnen',
  },
  profile: {
    copyChip: 'Chipnummer kopieren',
    chipCopied: 'Chipnummer kopiert.',
    callVet: 'Tierarztpraxis anrufen',
    year: 'Das Jahr in Stempeln',
    yearRange: (from: string, to: string) => `${from} bis ${to}`,
    legend: { done: 'erledigt', due: 'fällig', overdue: 'überfällig' },
    yearRow: (kind: string, done: string[], next: string | null) =>
      [
        `${kind}:`,
        done.length > 0 ? `erledigt im ${done.join(', ')}.` : 'in diesem Jahr nichts erledigt.',
        next ?? '',
        'Geschichte öffnen.',
      ]
        .filter(Boolean)
        .join(' '),
    nextDue: (date: string) => `nächste am ${date}`,
    nextDueLater: (monthYear: string) => `nächste im ${monthYear}`,
    overdueSince: (date: string) => `überfällig seit ${date}`,
    all: (name: string) => `Alles zu ${name}`,
    health: 'Gesundheit',
    entries: (count: number) => (count === 1 ? '1 Eintrag' : `${count} Einträge`),
    noEntries: 'Noch keine Einträge',
    addEntry: 'Eintrag hinzufügen',
    edit: 'Bearbeiten',
    archive: 'Archivieren',
    unarchive: 'Wieder aktiv setzen',
    remove: 'Löschen',
  },
  remove: {
    title: (name: string) => `${name} löschen?`,
    text: (name: string, entries: number, photos: number) =>
      `Das entfernt ${entries === 1 ? '1 Eintrag' : `${entries} Einträge`}, ${photos === 1 ? '1 Foto' : `${photos} Fotos`} und alle Erinnerungen für ${name}. Es lässt sich nicht rückgängig machen.`,
    confirm: (name: string) => `${name} und alle Daten löschen`,
    done: (name: string) => `${name} gelöscht.`,
  },
} as const;
