export const medicationsText = {
  title: 'Medikamente',
  newTitle: 'Neues Medikament',
  editTitle: 'Medikament bearbeiten',
  add: 'Medikament hinzufügen',
  empty: 'Noch keine Medikamente eingetragen.',
  notFound: 'Dieses Medikament gibt es nicht mehr.',
  cancel: 'Abbrechen',
  save: 'Sichern',
  saved: 'Medikament gesichert.',
  remove: 'Medikament löschen',
  removeTitle: 'Medikament löschen?',
  removeText: 'Das Medikament und seine Gaben verschwinden. Es lässt sich nicht rückgängig machen.',
  removed: 'Medikament gelöscht.',
  fields: {
    dog: 'Für',
    name: 'Name',
    nameHint: 'Zum Beispiel Apoquel 16 mg',
    dose: 'Dosis',
    doseHint: 'Zum Beispiel halbe Tablette',
    times: 'Uhrzeiten',
    timesHint: 'Wann am Tag? Mehrere sind möglich.',
    addTime: 'Uhrzeit hinzufügen',
    otherTime: 'Andere Uhrzeit',
    otherTimeError: 'Schreib die Uhrzeit so: 18:30.',
    removeTime: (time: string) => `Uhrzeit ${time} entfernen`,
    start: 'Beginn',
    end: 'Ende',
    endHint: 'Leer lassen, wenn es dauerhaft ist.',
    active: 'Läuft zurzeit',
  },
  /** Wie ein Medikament in der Liste steht. */
  summary: (dose: string, times: string[]) => `${dose}, ${times.join(' und ')}`,
  paused: 'Ruht',
  ended: (date: string) => `Bis ${date}`,
  give: (name: string, dog: string, time: string) =>
    `${name} für ${dog} um ${time} als gegeben stempeln`,
  givenLabel: (name: string, dog: string, time: string) =>
    `${name} für ${dog} gegeben um ${time}. Tippen, um es zurückzunehmen.`,
  givenAt: (time: string) => `Gegeben um ${time}`,
  announceGiven: (name: string, dog: string) => `${name} für ${dog} gegeben.`,
  announceOpen: (name: string, dog: string) => `${name} für ${dog} wieder offen.`,
  undoFailed: 'Das liess sich nicht zurücknehmen.',
} as const;
