export const pdfText = {
  section: 'PDF',
  screenTitle: 'PDF erstellen',
  cancel: 'Schliessen',
  diaryPeriod: 'Tagebuch im PDF',
  kinds: {
    vet: 'Für die Tierarztpraxis',
    sitter: 'Für den Hundesitter',
    poster: 'Vermisst-Plakat',
  },
  kindHints: {
    vet: 'Profil, Medikamente, Behandlungen der letzten zwölf Monate, Gewicht, Tagebuch.',
    sitter: 'Futter, Medikamente mit Uhrzeiten, Hinweise, Tierarztpraxis, deine Nummer.',
    poster: 'Grosses Foto, Merkmale, Chipnummer, wo und wann, Abreissstreifen.',
  },
  fileKinds: { vet: 'Tierarzt', sitter: 'Hundesitter', poster: 'Vermisst' },
  create: 'PDF erstellen und teilen',
  busy: 'PDF wird erstellt …',
  failed: 'Das PDF liess sich nicht erstellen. Versuch es nochmals.',
  webNotice:
    'In der Vorschau im Browser öffnet sich der Druckdialog. Dort kannst du «Als PDF sichern» wählen.',
  footer: (date: string) =>
    `Erstellt mit Hundebüechli am ${date}. Ersetzt nicht den Heimtierausweis und keine tierärztliche Beratung.`,
  vet: {
    title: (name: string) => `${name} – für die Tierarztpraxis`,
    profile: 'Profil',
    medications: 'Aktuelle Medikamente',
    noMedications: 'Keine laufenden Medikamente.',
    health: 'Behandlungen der letzten zwölf Monate',
    noHealth: 'Keine Einträge in den letzten zwölf Monaten.',
    columns: { kind: 'Art', date: 'Datum', product: 'Produkt', next: 'Nächste Fälligkeit' },
    weight: 'Gewicht',
    noWeight: 'Noch nicht gewogen.',
    weightColumns: { date: 'Datum', weight: 'Gewicht', difference: 'Veränderung' },
    diary: 'Tagebuch',
    noDiary: 'Keine Tagebucheinträge in diesem Zeitraum.',
  },
  sitter: {
    title: (name: string) => `${name} – für den Hundesitter`,
    food: 'Futter',
    medications: 'Medikamente',
    care: 'Gewohnheiten und Hinweise',
    allergies: 'Allergien',
    vet: 'Tierarztpraxis',
    owner: 'So erreichst du mich',
    nothing: 'Nichts eingetragen.',
  },
  poster: {
    heading: 'Vermisst',
    chip: 'Chipnummer',
    lastSeen: 'Zuletzt gesehen',
    call: 'Bitte anrufen:',
    strip: (name: string) => `${name} vermisst`,
    formTitle: 'Vermisst-Plakat',
    place: 'Wo zuletzt gesehen?',
    placeHint: 'Zum Beispiel Littau, beim Reussufer',
    when: 'Wann?',
    time: 'Uhrzeit',
    phone: 'Telefonnummer auf dem Plakat',
    phoneHint: 'Wird für den Abreissstreifen genutzt.',
    lastSeenText: (place: string, date: string, time: string) => `${place}, am ${date} um ${time}`,
  },
  facts: {
    breed: 'Rasse',
    sex: 'Geschlecht',
    born: 'Geboren',
    chip: 'Chipnummer',
    color: 'Farbe und Merkmale',
    allergies: 'Allergien',
    insurance: 'Versicherung',
    name: 'Name',
    phone: 'Telefon',
    email: 'E-Mail',
    address: 'Adresse',
  },
} as const;
